AWSTemplateFormatVersion: 2010-09-09

Parameters:
    HostedZoneNameParam:
      Type: String
      Default: tor-gu.com.
      Description: Hosted domain name, ending with period, e.g. tor-gu.com.
    DomainNameParam:
      Type: String
      Description: Domain name for api, e.g. api.tor-gu.com
    CertIdParam:
      Type: String
      Description: Id of certificate in AWS ACM
    LoggingBucketParam:
      Type: String
      Description: Name of S3 bucket for Logging
    LoggingPrefixParam:
      Type: String
      Description: Prefix for logs, e.g. "api/" or "test-api/"
    MunicipalitiesApiIdParam:
      Type: String
      Description: API ID for the Municipalities API      
    ElectionsApiIdParam:
      Type: String
      Description: API ID for the Municipalities API      
    EnabledParam:
      AllowedValues:
      - "true"
      - "false"
      Default: true
      Type: "String"
      Description: Distribution enabled or not


Resources:
  QueryStringsCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${AWS::StackName}QueryStringsCachePolicy"
        Comment: Cache using all params in the query string
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 1
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          QueryStringsConfig:
            QueryStringBehavior: all
  QueryStringsOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub "${AWS::StackName}TorguapiQueryStringsOriginRequestPolicy"
        Comment: Forward all query strings to the origin
        CookiesConfig:
          CookieBehavior: none
        HeadersConfig:
          HeaderBehavior: none
        QueryStringsConfig:
          QueryStringBehavior: all
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub 
        - "${DomainName} cloudfront distribution"
        - DomainName: !Ref DomainNameParam
        Enabled: !Ref EnabledParam
        Aliases: 
        - !Ref DomainNameParam
        ViewerCertificate:
          AcmCertificateArn: !Sub
          - "arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${CertId}"
          - CertId: !Ref CertIdParam
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        HttpVersion: http2
        Logging:
            Bucket: !Sub
            - "${LoggingBucket}.s3.amazonaws.com"
            - LoggingBucket: !Ref LoggingBucketParam
            Prefix: !Ref LoggingPrefixParam
        Origins:
        - Id: njmunicipalities-api
          DomainName: !Sub
          - "${MunicipalitiesApiId}.execute-api.us-east-1.amazonaws.com"
          - MunicipalitiesApiId: !Ref MunicipalitiesApiIdParam
          OriginPath: /Prod
          CustomOriginConfig: 
            OriginProtocolPolicy: https-only
            OriginSSLProtocols: 
            - TLSv1.2
        - Id: njelections-api
          DomainName: !Sub
          - "${ElectionsApiId}.execute-api.us-east-1.amazonaws.com"
          - ElectionsApiId: !Ref ElectionsApiIdParam
          OriginPath: /Prod
          CustomOriginConfig: 
            OriginProtocolPolicy: https-only
            OriginSSLProtocols: 
            - TLSv1.2
        CacheBehaviors:
        - PathPattern: /nj/counties/*
          TargetOriginId: njmunicipalities-api
          CachePolicyId: !Ref QueryStringsCachePolicy
          OriginRequestPolicyId: !Ref QueryStringsOriginRequestPolicy
          ViewerProtocolPolicy: https-only
          Compress: true
        - PathPattern: /nj/municipalities/*
          TargetOriginId: njmunicipalities-api
          CachePolicyId: !Ref QueryStringsCachePolicy
          OriginRequestPolicyId: !Ref QueryStringsOriginRequestPolicy
          ViewerProtocolPolicy: https-only
          Compress: true
        - PathPattern: /nj/elections/*
          TargetOriginId: njelections-api
          CachePolicyId: !Ref QueryStringsCachePolicy
          OriginRequestPolicyId: !Ref QueryStringsOriginRequestPolicy
          ViewerProtocolPolicy: https-only
          Compress: true
        DefaultCacheBehavior:
          TargetOriginId: njmunicipalities-api
          CachePolicyId: !Ref QueryStringsCachePolicy
          OriginRequestPolicyId: !Ref QueryStringsOriginRequestPolicy
          ViewerProtocolPolicy: https-only
          ViewerProtocolPolicy: https-only
          Compress: true
      Tags:
        - Key: project
          Value: torgu-api
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref DomainNameParam
      HostedZoneName: !Ref HostedZoneNameParam
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudfrontDistribution.DomainName
        # "This is always the hosted zone ID when you create an alias record that routes traffic to a CloudFront distribution."
        HostedZoneId: Z2FDTNDATAQYW2
