version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - export ElectionsApiId="$(aws cloudformation describe-stacks 
                                    --stack-name ${ENV_CURRENT_STACK} 
                                    --region ${ENV_REGION} 
                                    --query "Stacks[0].Outputs[?OutputKey=='ElectionsApiIdParam'].OutputValue" --output text)"
      - export MunicipalitiesApiId="$(aws cloudformation describe-stacks 
                                    --stack-name ${ENV_CURRENT_STACK} 
                                    --region ${ENV_REGION} 
                                    --query "Stacks[0].Outputs[?OutputKey=='MunicipalitiesApiIdParam'].OutputValue" --output text)"
      - export LoggingBucket="$(aws cloudformation describe-stacks 
                                    --stack-name ${ENV_CURRENT_STACK} 
                                    --region ${ENV_REGION} 
                                    --query "Stacks[0].Outputs[?OutputKey=='LoggingBucketParam'].OutputValue" --output text)"
      - export LoggingPrefix="$(aws cloudformation describe-stacks 
                                    --stack-name ${ENV_CURRENT_STACK} 
                                    --region ${ENV_REGION} 
                                    --query "Stacks[0].Outputs[?OutputKey=='LoggingPrefixParam'].OutputValue" --output text)"
  build:
    commands:
      - . ./assume-role.sh ${ENV_PIPELINE_EXECUTION_ROLE} deploy
      - aws cloudformation deploy --template-file ${ENV_TEMPLATE}
                    --stack-name ${ENV_STACK_NAME}
                    --capabilities CAPABILITY_IAM
                    --region ${ENV_REGION}
                    --role-arn ${ENV_CLOUDFORMATION_EXECUTION_ROLE}
                    --no-fail-on-empty-changeset
                    --parameter-overrides \
                        HostedZoneNameParam=${ENV_HOSTED_ZONE_NAME}           \
                        DomainNameParam=${ENV_DOMAIN_NAME}                    \
                        CertIdParam=${ENV_CERT_ID}                            \
                        LoggingBucketParam=$LoggingBucket                     \
                        LoggingPrefixParam=$LoggingPrefix                     \
                        MunicipalitiesApiIdParam=$MunicipalitiesApiIdParam    \
                        ElectionsApiIdParam=$ElectionsApiId
